version: '2'
services:
    hoard-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/hoard/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=hoard
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
